### ISSUE TITLE
Accès limité site les ailleurs - wordpress 

### ISSUE THREAD

**Issue by ElisaK1** [CRC-Studio/lesailleurs#18]
Hello ! 

Je n'arrive plus accéder à l'adresse https://lesailleurs.crc-studio.fr/wp-login.php
Serveur et site inaccessibles ou introuvables... 

J'ai pourtant toujours réussi jusqu'ici. 

Comment faire ? 

Merci beaucoup ! 

Elisa

**Comment by RemiBLoizeau** [comment]
Hello Elisa,

le site lesailleurs.crc-studio.fr est désormais fermé.
↳ Il s'agissait d'un espace de test avant la mise en ligne du site.

Maintenant que le site est en ligne, RDV sur [lesailleurs.art/login](https://lesailleurs.art/wp-login.php) 😉

Bonne journée !
— r.
