### ISSUE TITLE
créer une nationalité en anglais : existe déjà VS pas trouvé SAFARI

### ISSUE THREAD

**Issue by ValentinFabbula** [CRC-Studio/lesailleurs#5]
impossible de créer 'French' en anglais dans nationalités car existe déjà, et ne le trouve pas dans le menu déroulant

<img width="476" alt="Screenshot 2021-02-17 at 11 23 07" src="https://user-images.githubusercontent.com/79197356/108190790-b2ea9480-7112-11eb-9ee9-a841fa2d2118.png">
<img width="394" alt="Screenshot 2021-02-17 at 11 22 59" src="https://user-images.githubusercontent.com/79197356/108190799-b3832b00-7112-11eb-9cf4-e5c2082f9245.png">

**Comment by RemiBLoizeau** [comment]
Oh ! Notre première Issue 🎉

La Nationalité _French_ existait bel et bien, mais il s'agissait d'une Nationalité appartenant à la version Française.
Voir → https://lesailleurs.crc-studio.fr/wp-admin/edit-tags.php?taxonomy=nationalite

![image](https://user-images.githubusercontent.com/74113050/108447637-99426d80-7236-11eb-875d-249154b5c863.png)

Normalement, c'est corrigé !
