### ISSUE TITLE
Ajouter une profession en anglais : menu déroulant ne fonctionne pas

### ISSUE THREAD

**Issue by ValentinFabbula** [CRC-Studio/lesailleurs#6]
<img width="572" alt="Screenshot 2021-02-23 at 14 38 21" src="https://user-images.githubusercontent.com/79197356/108851758-12e6ac80-75e5-11eb-80d5-529965946c8c.png">
<img width="335" alt="Screenshot 2021-02-23 at 14 38 15" src="https://user-images.githubusercontent.com/79197356/108851763-137f4300-75e5-11eb-87bd-a6752fc0202b.png">
<img width="602" alt="Screenshot 2021-02-23 at 14 38 00" src="https://user-images.githubusercontent.com/79197356/108851765-1417d980-75e5-11eb-86e1-b332fdad2a5b.png">

Hello Rémi ! En remplissant la page d'Eric Chahi en anglais j'ai voulu ajouter des professions. Créées dans la base de donnée, elles n'apparaissent pas dans le menu déroulant "Profession" et sont pas reconnues quand je les recherche

Bises

**Comment by RemiBLoizeau** [comment]
Hello @ValentinFabbula, 
pour le moment, il semblerait qu'il ne soit pas possible de créer des profession directement en anglais. Le temps que nous trouvions un fix pour ce problème :
**01 —** Créer les _Professions_ en français
**02 —**  RDV sur la [page listant _Professsions_](https://lesailleurs.crc-studio.fr/wp-admin/edit-tags.php?taxonomy=profession&post_type=auteur)
**03 —** Pour chaque _Profession_ en français, cliquer sur le  **+** pour dupliquer la _Profession_ sélectionner et la traduire en anglais.

![image](https://user-images.githubusercontent.com/74113050/110227641-d6625d00-7ed0-11eb-95b3-bd41fe30c447.png)
