### ISSUE TITLE
page édition vide sur backoffice (safari)

### ISSUE THREAD

**Issue by ValentinFabbula** [CRC-Studio/lesailleurs#7]
<img width="996" alt="Screenshot 2021-02-24 at 18 25 09" src="https://user-images.githubusercontent.com/79197356/109040114-dd69be00-76cd-11eb-9164-c045d5b1687e.png">

hola ! page édition vide quand je tente de la modifier, j'ai vidé mon cache ^^'

**Comment by RemiBLoizeau** [comment]
Hello Valentin,  ici nous avons accès à l'interface. Est-ce que tu l'as aussi de ton côté ?
![image](https://user-images.githubusercontent.com/74113050/110227335-977ed800-7ecd-11eb-944a-30fab98e3895.png)

**Comment by YokoHomareda** [comment]
teste issue by creation team
