### ISSUE TITLE
Version FR > ENGL

### ISSUE THREAD

**Issue by ElisaK1** [CRC-Studio/lesailleurs#8]
En remplissant page oeuvre dans l'onglet description, lorsque que je change le texte fr vers l'anglais en activant bien la langue dans le menu, rien ne change. 
Si je change le texte, il change pour les deux langues et ne s'adapte pas selon langue choisie. CF captures d'écran jointes 

<img width="1440" alt="Capture d’écran 2021-02-24 à 18 24 57" src="https://user-images.githubusercontent.com/79597531/109040784-97612a00-76ce-11eb-932d-471709150838.png">

<img width="1440" alt="Capture d’écran 2021-02-24 à 18 24 52" src="https://user-images.githubusercontent.com/79597531/109040767-929c7600-76ce-11eb-87db-f1da18604d95.png">

**Comment by RemiBLoizeau** [comment]
Hello  @ElisaK1, merci pour commentaire.

Le système de langue fonctionne comme un miroir : il faut dédoubler chaque page. Lorsque vous changez la langue, vous ne passer pas _de l'autre côté du miroir_. Les textes restes donc identique. 


![Plan de travail 37-80](https://user-images.githubusercontent.com/74113050/110227382-4d4a2680-7ece-11eb-8c2d-00795ad0588b.jpg)

![image](https://user-images.githubusercontent.com/74113050/110227438-eb3df100-7ece-11eb-984d-1771c6a418bf.png)
